/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionbiblioteca;

/**
 *
 * @author britz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal2
     */
    InsertarUsuario InsertarUsuario;
    ListaUsuario ListaUsuario;
    ConsultarUsuario ConsultarUsuario;
    InsertarLibros InsertarLibros;
    BuscarLibros BuscarLibros;
    InsertarPrestamo InsertarPrestamo;
    ConsultarPrestamo ConsultarPrestamo;
    public Principal() {
        initComponents();
         this.setLocationRelativeTo(null);
        InsertarUsuario = new InsertarUsuario();
        add(InsertarUsuario);
        ListaUsuario = new ListaUsuario();
        add(ListaUsuario);
        ConsultarUsuario = new ConsultarUsuario();
        add(ConsultarUsuario);
        InsertarLibros = new InsertarLibros();
        add(InsertarLibros);
        BuscarLibros = new BuscarLibros();
        add(BuscarLibros);
        InsertarPrestamo = new InsertarPrestamo();
        add(InsertarPrestamo);
        ConsultarPrestamo = new ConsultarPrestamo();
        add(ConsultarPrestamo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        bRegistrar = new javax.swing.JMenuItem();
        bLista = new javax.swing.JMenuItem();
        bConsultar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        bRegistrar2 = new javax.swing.JMenuItem();
        bLista2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        bInsertar3 = new javax.swing.JMenuItem();
        bConsulta3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Clientes");

        bRegistrar.setText("Registrar");
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });
        jMenu1.add(bRegistrar);

        bLista.setText("Lista");
        bLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListaActionPerformed(evt);
            }
        });
        jMenu1.add(bLista);

        bConsultar.setText("Consultar");
        bConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(bConsultar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Libros");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        bRegistrar2.setText("Registrar");
        bRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrar2ActionPerformed(evt);
            }
        });
        jMenu2.add(bRegistrar2);

        bLista2.setText("Lista");
        bLista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLista2ActionPerformed(evt);
            }
        });
        jMenu2.add(bLista2);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Prestamo");

        bInsertar3.setText("Insertar");
        bInsertar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertar3ActionPerformed(evt);
            }
        });
        jMenu5.add(bInsertar3);

        bConsulta3.setText("Consultar");
        bConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsulta3ActionPerformed(evt);
            }
        });
        jMenu5.add(bConsulta3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
        // TODO add your handling code here:
        InsertarUsuario.setVisible(true);
        ConsultarUsuario.setVisible(false);
        ListaUsuario.setVisible(false);
        BuscarLibros.setVisible(false);
        InsertarLibros.setVisible(false);
        InsertarPrestamo.setVisible(false);
        ConsultarPrestamo.setVisible(false);
    }//GEN-LAST:event_bRegistrarActionPerformed

    private void bListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListaActionPerformed
        // TODO add your handling code here:
        ListaUsuario.setVisible(true);
        InsertarUsuario.setVisible(false);
        ConsultarUsuario.setVisible(false);
        BuscarLibros.setVisible(false);
        InsertarLibros.setVisible(false);
        InsertarPrestamo.setVisible(false);
        ConsultarPrestamo.setVisible(false);
    }//GEN-LAST:event_bListaActionPerformed

    private void bConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarActionPerformed
        // TODO add your handling code here:
        ConsultarUsuario.setVisible(true);
        ListaUsuario.setVisible(false);
        InsertarUsuario.setVisible(false);
        BuscarLibros.setVisible(false);
        InsertarLibros.setVisible(false);
        InsertarPrestamo.setVisible(false);
        ConsultarPrestamo.setVisible(false);
    }//GEN-LAST:event_bConsultarActionPerformed

    private void bRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrar2ActionPerformed
        // TODO add your handling code here:
        InsertarLibros.setVisible(true);
        BuscarLibros.setVisible(false);
        ConsultarUsuario.setVisible(false);
        ListaUsuario.setVisible(false);
        InsertarUsuario.setVisible(false);
        InsertarPrestamo.setVisible(false);
        ConsultarPrestamo.setVisible(false);
    }//GEN-LAST:event_bRegistrar2ActionPerformed

    private void bLista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLista2ActionPerformed
        // TODO add your handling code here:
        BuscarLibros.setVisible(true);
        InsertarLibros.setVisible(false);
        ConsultarUsuario.setVisible(false);
        ListaUsuario.setVisible(false);
        InsertarUsuario.setVisible(false);
        InsertarPrestamo.setVisible(false);
        ConsultarPrestamo.setVisible(false);

    }//GEN-LAST:event_bLista2ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void bInsertar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertar3ActionPerformed
        // TODO add your handling code here:
        InsertarPrestamo.setVisible(true);
        ConsultarPrestamo.setVisible(false);
        BuscarLibros.setVisible(false);
        InsertarLibros.setVisible(false);
        ConsultarUsuario.setVisible(false);
        ListaUsuario.setVisible(false);
        InsertarUsuario.setVisible(false);
    }//GEN-LAST:event_bInsertar3ActionPerformed

    private void bConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsulta3ActionPerformed
        // TODO add your handling code here:
        ConsultarPrestamo.setVisible(true);
        InsertarPrestamo.setVisible(false);
        BuscarLibros.setVisible(false);
        InsertarLibros.setVisible(false);
        ConsultarUsuario.setVisible(false);
        ListaUsuario.setVisible(false);
        InsertarUsuario.setVisible(false);
    }//GEN-LAST:event_bConsulta3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bConsulta3;
    private javax.swing.JMenuItem bConsultar;
    private javax.swing.JMenuItem bInsertar3;
    private javax.swing.JMenuItem bLista;
    private javax.swing.JMenuItem bLista2;
    private javax.swing.JMenuItem bRegistrar;
    private javax.swing.JMenuItem bRegistrar2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
